### ISSUE TITLE
piraeus-datastore on raspi

### ISSUE THREAD

**Issue by vdveldet** [piraeusdatastore/piraeus#206]
Hi,

When trying to install piraeus-datastoreon an raspberry pi 5, using latest bookworm I get the error below.

```shell 
kubectl -n piraeus-datastore logs linstor-satellite.raspi5-tsdg8 --all-containers

Need a git checkout to regenerate drbd/.drbd_git_revision
make[1]: Entering directory '/tmp/pkg/drbd-9.2.13/drbd'

    Calling toplevel makefile of kernel source tree, which I believe is in
    KDIR=/lib/modules/6.6.51+rpt-rpi-2712/build

make -C /lib/modules/6.6.51+rpt-rpi-2712/build    "PRE_CFLAGS=" M=/tmp/pkg/drbd-9.2.13/drbd obj-m=dummy-for-compat.o dummy-for-compat-h.o
make[1]: Leaving directory '/tmp/pkg/drbd-9.2.13/drbd'
/usr/src/linux-headers-6.6.51+rpt-common-rpi/Makefile:1032: /usr/src/linux-headers-6.6.51+rpt-common-rpi/scripts/Makefile.extrawarn: No such file or directory
make[2]: *** No rule to make target '/usr/src/linux-headers-6.6.51+rpt-common-rpi/scripts/Makefile.extrawarn'.  Stop.
make[1]: *** [Makefile:236: compat.h] Error 2
make: *** [Makefile:131: module] Error 2

Could not find the expexted *.ko, see stderr for more details
Error from server (BadRequest): container "drbd-shutdown-guard" in pod "linstor-satellite.raspi5-tsdg8" is waiting to start: PodInitializing
                                                                                                     
```
The kernel headers are installed with the command below.
`
```shell
apt-get install -y linux-headers-$(uname -r)
```
The same procedure worked on an amd64

**Comment by WanzenBug** [comment]
See also https://github.com/piraeusdatastore/piraeus-operator/issues/805

The trouble is that Raspi has their own kernel flavor, and the debian packaging moves some stuff out of `/usr/src` and only symlinks them. Case in point, if you run `readlink -f /usr/src/linux-headers-6.6.51+rpt-common-rpi/scripts/Makefile.extrawarn` on your host, it will point to some `/usr/lib` directory (I think). You can add that directory to the container by adding the following configuration:

```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: raspi-kbuild
spec:
  podTemplate:
    spec:
      volumes:
      - name: raspi-kbuild-tools
        hostPath:
          type: Directory
          path: /usr/lib/linux-kbuild- # insert the right path
     initContainers:
     - name: drbd-module-loader
       volumeMounts:
       - mountPath:  /usr/lib/linux-kbuild- # insert the right path, again
         name: raspi-kbuild-tools
         readOnly: true
```

**Comment by vdveldet** [comment]
I have implemented the below and that is indeed working.
Thanks for the response.

```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: raspi-kbuild
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  podTemplate:
    spec:
      volumes:
      - name: raspi-kbuild-tools
        hostPath:
          type: Directory
          path: /usr/lib/linux-kbuild-6.6.51+rpt/
      initContainers:
      - name: drbd-module-loader
        volumeMounts:
        - mountPath:  /usr/lib/linux-kbuild-6.6.51+rpt/
          name: raspi-kbuild-tools
          readOnly: true

```
