### ISSUE TITLE
Schedule only on workers node

### ISSUE THREAD

**Issue by bratao** [piraeusdatastore/piraeus#24]
Hello, 

Thank you for this awesome technology, I´m very excited to try. 
I installed using the helm, but one think. It also installed on the control node. I think that would be preferred in install only on nodes with the label node-role.kubernetes.io/worker . Or I´m missing something?

**Comment by alexzhc** [comment]
You should try the simple `kubectl apply -f all.yaml`. The node affinity for piraeus-node requires the node to 1. have label `piraeus/node=true` and 2. is not a k8s master node. If you have other affinity need, please edit it further. 

```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
```
