### ISSUE TITLE
Piraeus/linstor configuration lost after full cluster reboot

### ISSUE THREAD

**Issue by lrijneveld** [piraeusdatastore/piraeus#32]
The current deployment uses a statefullset with 3 etcd pods and is setup to always start without any data. It seems that this is the reason why we loose our linstor configuration after a full reboot of the cluster (reproducable by deleting all etcd pods simultaniously).

We were planning to "just" back the etcd pods with a hostPath volume for data. However since there has been put considered effort in the init container (and stopHook) in making sure that the data folder is moved/archived we are hesitant in doing so.

Would it be possible to support durable etcd data (surviving a cluster wide outage of the etcd service)? Or is there an other way envisioned to retain the linstor configuration after such an event?

**Comment by alexzhc** [comment]
@lrijneveld 
1. you should use node affinity to fix etcd pods on three different nodes. 
2. current piraeus all.yaml has already consolidated etcd data on /var/lib/piraeus/etcd

```
        volumeMounts:
        - name: data
          mountPath: /var/lib/etcd
      volumes:
        hostPath:
          path: /var/lib/piraeus/etcd
```
